### ISSUE TITLE
stuck on load screen

### ISSUE THREAD

**Issue by fortniteil** [xander1998/xrplife#2]
hi so they bug is is not connecting to the server 

photo 👍 

https://steamuserimages-a.akamaihd.net/ugc/948468807418124727/411831CDB5723D22C7AF35C5A74097F072507532/

**Comment by xander1998** [comment]
You need to go into the "fivem-map-skater" resource and set this

resource_type 'map' { gameTypes = { fivem = true } }

to this

resource_type 'map' { gameTypes = { XRPLife = true } }

**Comment by OfficialDarkzy** [comment]
4head

**Comment by xander1998** [comment]
I am closing this as no more comments have been received since Dec 10, 2018.
