### ISSUE TITLE
help me pls

### ISSUE THREAD

**Issue by w1nj3r** [xander1998/xrplife#3]
![default](https://user-images.githubusercontent.com/44757627/51080629-27f37080-16e8-11e9-945c-71a3d3b53833.png)

**Comment by xander1998** [comment]
Do you have externalsql loaded as a resource.

**Comment by xander1998** [comment]
You have to install my resource "externalsql" that is also on my github repos.

**Comment by w1nj3r** [comment]
>           You have to install my resource "externalsql" that is also on my github repos.

ok I download that, and place in resource, but when start, I have many errors

Error running system event handling function for resource externalsql: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/json.lua:397: bad argument #1 to 'strfind' (string expected, got nil)
stack traceback:
        [C]: in function 'string.find'
        citizen:/scripting/lua/json.lua:397: in upvalue 'scanwhite'
        citizen:/scripting/lua/json.lua:553: in function <citizen:/scripting/lua/json.lua:551>
        (...tail calls...)
        server.lua:54: in local 'userCallback'
        citizen:/scripting/lua/scheduler.lua:318: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>

**Comment by xander1998** [comment]
Did you actually setup the MySQL configs properly

XRPLife was never finished and never will be. I only left the code up there for someone else to look at. Installing it isn't really for just anyone as you need knowledge of NodeJS API's and some pretty good knowledge on installing resources.

**Comment by xander1998** [comment]
I am gonna close this as no more responses have occured in a week.
